# Generated by Django 3.0.8 on 2020-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_U_O', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
