# Generated by Django 3.0.8 on 2020-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_U_O', '0002_auto_20200718_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('email', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
