# Generated by Django 3.0.8 on 2020-07-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_U_O', '0004_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
